<<<<<<< HEAD

=======
>>>>>>> 26795d121168eacaebe7c013cc7fa0474893799f
[build]
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200
[[redirects]]
  from = "/cancel"
  to = "/cancel.html"
  status = 200


